// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IQ8KLIEMRG6E9gbmm0GXcFifCz-RRqc',
    appId: '1:115514690191:web:c5ea8758ac5d6390647efa',
    messagingSenderId: '115514690191',
    projectId: 'uni-map-fe7c6',
    authDomain: 'uni-map-fe7c6.firebaseapp.com',
    storageBucket: 'uni-map-fe7c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnJlNN5WyteD2AqD1aKq0mS1wAKl4mhp8',
    appId: '1:115514690191:android:8ff5709e13bc3fa7647efa',
    messagingSenderId: '115514690191',
    projectId: 'uni-map-fe7c6',
    storageBucket: 'uni-map-fe7c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfglP_s9Vwgbytf-1q_odKPa-aVoTtl7U',
    appId: '1:115514690191:ios:a18b9464f7ab5e36647efa',
    messagingSenderId: '115514690191',
    projectId: 'uni-map-fe7c6',
    storageBucket: 'uni-map-fe7c6.appspot.com',
    iosBundleId: 'com.example.uniMap',
  );
}
